spring:
  application:
    name: servicio-de-clientes-ha

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zona1
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/,http://localhost:3002/eureka/,http://localhost:3003/eureka/

server:
  port: ${PORT:9000}

---
# Para utilizar este perfil
# java -D"spring.profiles.active=nodo1" -jar target/eureka-ha-clientes-0.1.0-SNAPSHOT.jar
spring:
  config:
    activate:
      on-profile: nodo1

eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zona1
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:3001/eureka/}
#      defaultZone: http://localhost:3001/eureka/,http://localhost:3002/eureka/,http://localhost:3003/eureka/
server:
  port: ${PORT:9001}

---
# Para utilizar este perfil
# java -D"spring.profiles.active=nodo2" -jar target/eureka-ha-clientes-0.1.0-SNAPSHOT.jar
spring:
  config:
    activate:
      on-profile: nodo2

eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zona2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:3002/eureka/}
#      defaultZone: http://localhost:3001/eureka/,http://localhost:3002/eureka/,http://localhost:3003/eureka/
server:
  port: ${PORT:9002}

---
# Para utilizar este perfil
# java -D"spring.profiles.active=nodo3" -jar target/eureka-ha-clientes-0.1.0-SNAPSHOT.jar
spring:
  config:
    activate:
      on-profile: nodo3

eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zona3
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:3003/eureka/}
#      defaultZone: http://localhost:3001/eureka/,http://localhost:3002/eureka/,http://localhost:3003/eureka/
server:
  port: ${PORT:9003}
